version: 0.0
os: linux

files:
  - source: .
    destination: /home/ubuntu/myapp

hooks:
  BeforeInstall:
    - location: scripts/scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/scripts/start_server.sh
      timeout: 300
      runas: ubuntu

  AfterAllowTestTraffic:
    - location: scripts/scripts/post_script.sh
      timeout: 300
      runas: ubuntu
