version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing global dependencies...
      - npm install -g mocha

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install unit.js

  build:
    commands:
      - echo Running tests...
      - mocha test.js

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - test.js
    - appspec.yml
    - scripts/**
    - node_modules/**

  discard-paths: no
